"use client";
import {useEffect,useMemo,useState} from 'react';
import type {PilotApiClient} from './api-client';
import {emptyReportFilter,filterReport,reportMetrics,reportCsv,type ReportRow} from './pilot-operations-model';
type Result={rows:ReportRow[];generatedAt:string;offeredMinutes:number|null;truncated?:boolean};
export function PilotReporting({api,previewMode}:{api:PilotApiClient;previewMode:boolean}){
 const [data,setData]=useState<Result>({rows:[],generatedAt:'',offeredMinutes:null}),[message,setMessage]=useState(''),[filter,setFilter]=useState(emptyReportFilter),[tab,setTab]=useState('Overview'),[source,setSource]=useState('all'),[page,setPage]=useState(0);
 useEffect(()=>{let active=true;const timer=setTimeout(()=>void api.request<Result>('/api/pilot/reports').then(v=>{if(active)setData(v);}).catch(e=>{if(active)setMessage(e.message);}),0);return()=>{active=false;clearTimeout(timer);};},[api]);
 const rows=useMemo(()=>filterReport(data.rows,filter).filter(r=>source==='all'||r.source===source).filter(r=>tab==='Visits'?r.kind==='visit':tab==='Events'?r.kind==='event':true),[data.rows,filter,source,tab]);
 const metrics=reportMetrics(rows,null); // Availability must be scoped to these exact filters before a denominator can be used.
 const fields=['student','provider','service','topic','status','campus','location'] as const;
 const exportData=async()=>{try{if(!previewMode)await api.request('/api/pilot/report_export',{method:'POST',body:{filter,source,tab}});const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([reportCsv(rows)],{type:'text/csv;charset=utf-8'}));link.download='compass-pilot-report.csv';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);}catch(e){setMessage(e instanceof Error?e.message:'Export failed.');}};
 return <section><h2>Data dashboard</h2><p>Fictional student pilot · campus time: America/Los_Angeles. {data.generatedAt?`Refreshed ${new Date(data.generatedAt).toLocaleString()}`:'Awaiting report data.'}</p><nav aria-label="Report views">{['Overview','Visits','Events','Engagement','Utilization'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>{setTab(t);setPage(0);}}>{t}</button>)}</nav><div className="pilot-filters"><label>From<input type="date" value={filter.from} onChange={e=>{setFilter({...filter,from:e.target.value});setPage(0);}}/></label><label>Through<input type="date" min={filter.from} value={filter.to} onChange={e=>{setFilter({...filter,to:e.target.value});setPage(0);}}/></label>{fields.map(key=>{const choices=new Map(data.rows.map(r=>key==='student'?[r.studentId||'',r.studentName]:key==='provider'?[r.providerId||'',r.providerName]:[r[key],r[key]]));return <label key={key}>{key}<select value={filter[key]} onChange={e=>{setFilter({...filter,[key]:e.target.value});setPage(0);}}><option value="">All</option>{[...choices].filter(([v])=>v).map(([v,name])=><option key={v} value={v}>{name||v}</option>)}</select></label>})}<label>Data source<select value={source} onChange={e=>{setSource(e.target.value);setPage(0);}}><option value="all">All sources (no inferred merging)</option>{[...new Set(data.rows.map(r=>r.source))].map(s=><option key={s}>{s}</option>)}</select></label></div><div className="pilot-metrics">{Object.entries(metrics).map(([k,v])=><article key={k}><small>{k.replace(/([A-Z])/g,' $1')}</small><strong>{v===null?'Unavailable':k==='utilization'?`${Math.round(v*100)}%`:v}</strong></article>)}</div>{tab==='Utilization'?<p>Utilization requires offered appointment minutes for the same providers and date range. Missing availability is not treated as zero.</p>:null}{tab==='Engagement'?<p>Repeat participants have at least two completed visits or attended events in this selection.</p>:null}{data.truncated?<p role="alert">This selection exceeds 10,000 rows. Export is disabled to prevent an incomplete report.</p>:null}<button disabled={!!data.truncated} onClick={()=>void exportData()}>Export selected data</button><table><thead><tr><th>Status</th><th>Date</th><th>Student</th><th>Provider</th><th>Service</th><th>Location</th><th>Scheduled / reported minutes</th><th>Source</th></tr></thead><tbody>{rows.slice(page*50,(page+1)*50).map(r=><tr key={r.id}><td>{r.status}<small>{r.attendance||'Attendance not recorded'}</small></td><td>{new Date(r.startsAt).toLocaleString('en-US',{timeZone:'America/Los_Angeles'})}</td><td>{r.studentName||'Unlinked'}</td><td>{r.providerName}</td><td>{r.service}</td><td>{r.location||'Not recorded'}</td><td>{r.scheduledMinutes} / {r.reportedMinutes??'Not reported'}</td><td>{r.source}</td></tr>)}</tbody></table><button disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><button disabled={(page+1)*50>=rows.length} onClick={()=>setPage(p=>p+1)}>Next</button><p role="status">{message}</p></section>;
}
