"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import type {PilotApiClient} from './api-client';
import {ticketStatuses,sanitizedPage,type SupportTicket,type TicketReply,type DevelopmentJob,type AutomationSchedule,type AutomationRun} from './pilot-operations-model';
import {PilotStudentView} from './pilot-student-view';
import {PilotReporting} from './pilot-reporting';
import venues from './henderson-venues.json';
import './pilot-operations.css';

type Props={api:PilotApiClient;workspace:string;creator:boolean;previewMode:boolean;staff?:boolean};
const label=(text:string)=>text.replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());
export function PilotOperationsLauncher(props:Props){
 const [open,setOpen]=useState(false);
 return <><button className="text-button" onClick={()=>setOpen(true)}>Support / Request a Feature</button>{props.creator?<button className="text-button" onClick={()=>setOpen(true)}>Creator operations</button>:null}{open?<OperationsDialog {...props} onClose={()=>setOpen(false)}/>:null}</>;
}
export function OperationsDialog({api,workspace,creator,previewMode,staff,onClose}:Props&{onClose:()=>void}){
 const ref=useRef<HTMLDialogElement>(null),[tab,setTab]=useState('support');
 useEffect(()=>{ref.current?.showModal();},[]);
 const tabs=creator?['support','development','health','automations','reporting','student_view','venues','privacy']:staff?['support','reporting','student_view','venues']:['support'];
 return <dialog className="pilot-operations" ref={ref} onCancel={onClose} aria-label="Compass support and operations"><header><div><small>{previewMode?'Fictional demo · no external actions':'Roseman staff pilot'}</small><h1>{creator?'Creator operations':'Support / Request a Feature'}</h1></div><button onClick={onClose} aria-label="Close support and operations">Close</button></header><nav aria-label="Operations sections">{tabs.map(t=><button key={t} aria-pressed={t===tab} onClick={()=>setTab(t)}>{label(t)}</button>)}</nav><main>
 {tab==='student_view'?<PilotStudentView api={api} creator={creator} previewMode={previewMode}/>:null}
 {tab==='support'?<SupportInbox api={api} workspace={workspace} creator={creator}/>:null}
 {tab==='development'?<DevelopmentWorkspace api={api} previewMode={previewMode}/>:null}
 {tab==='automations'?<AutomationPanel api={api}/>:null}
 {tab==='health'?<HealthPanel api={api}/>:null}
 {tab==='reporting'?<PilotReporting api={api} previewMode={previewMode}/>:null}
 {tab==='venues'?<VenueDirectory/>:null}
 {tab==='privacy'?<section><h2>Pilot privacy and handoff</h2><p>Thirty Roseman staff. Fictional student records. Guests, student sign-ins, Wellness and research instruments remain gated.</p><ul><li>Only the Creator manages support tickets. Requesters see their own tickets and public replies.</li><li>Staff student-facing views are read-only and limited to existing authorized assignments.</li><li>Private advising notes and research responses do not belong in support tickets, diagnostics, email, or development prompts.</li><li>Development uses separate checkouts. Passing checks and approval of the reviewed revision are required before a release.</li><li>Institutional retention, incident ownership and recovery targets must be recorded before real student data is introduced.</li><li>Local worker automation requires this computer to be on. Email delivery runs independently on the hosted backend.</li></ul><p>Activation dependencies: IT SSO metadata, email service configuration, verified Summerlin rooms, and a paired local worker.</p></section>:null}
 </main></dialog>;
}
function SupportInbox({api,workspace,creator}:Omit<Props,'previewMode'>){
 const [tickets,setTickets]=useState<SupportTicket[]>([]),[offset,setOffset]=useState(0),[selected,setSelected]=useState<{ticket:SupportTicket;replies:TicketReply[]}|null>(null);
 const [subject,setSubject]=useState(''),[description,setDescription]=useState(''),[kind,setKind]=useState('support'),[impact,setImpact]=useState('question'),[reply,setReply]=useState(''),[internal,setInternal]=useState(false),[instruction,setInstruction]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const requestKey=useRef(crypto.randomUUID());
 const load=useCallback(async()=>setTickets(await api.request<SupportTicket[]>(`/api/pilot/tickets?offset=${offset}`)),[api,offset]);
 useEffect(()=>{const timer=setTimeout(()=>void load().catch(e=>setMessage(e.message)),0);return()=>clearTimeout(timer);},[load]);
 const run=async(task:()=>Promise<void>)=>{setBusy(true);setMessage('');try{await task();}catch(e){setMessage(e instanceof Error?e.message:'Request failed.');}finally{setBusy(false);}};
 const open=async(id:string)=>setSelected(await api.request(`/api/pilot/ticket_detail?ticketId=${id}`));
 return <div className="pilot-columns"><section><h2>{creator?'Support queue':'My tickets'}</h2><button onClick={()=>void run(load)}>Refresh</button><ul className="pilot-ticket-list">{tickets.map(t=><li key={t.id}><button onClick={()=>void run(()=>open(t.id))}><strong>{t.subject}</strong><small>{label(t.status)} · {t.workspace} · {new Date(t.updated_at).toLocaleDateString()}</small></button></li>)}</ul>{!tickets.length?<p>No tickets on this page.</p>:null}<button disabled={!offset||busy} onClick={()=>setOffset(n=>Math.max(0,n-50))}>Previous</button><button disabled={tickets.length<50||busy} onClick={()=>setOffset(n=>n+50)}>Next</button>
 <details><summary>Submit a new request</summary><form onSubmit={e=>{e.preventDefault();void run(async()=>{await api.request('/api/pilot/ticket_create',{method:'POST',body:{workspace,kind,subject,description,impact,pageContext:sanitizedPage(window.location.pathname),requestKey:requestKey.current}});requestKey.current=crypto.randomUUID();setSubject('');setDescription('');await load();setMessage('Request saved. Follow its status here.');});}}><label>Request type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="support">Support</option><option value="feature">New feature</option></select></label><label>Subject<input required maxLength={160} value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>Impact<select value={impact} onChange={e=>setImpact(e.target.value)}><option value="question">Question or suggestion</option><option value="blocked">My work is blocked</option><option value="disruption">Service disruption</option></select></label><label>Description<textarea required maxLength={6000} value={description} onChange={e=>setDescription(e.target.value)}/></label><p>Describe the workflow. Leave out private student records and passwords.</p><button disabled={busy}>Submit request</button></form></details></section>
 <section>{selected?<><h2>{selected.ticket.subject}</h2><p>{selected.ticket.description}</p><small>{selected.ticket.id}</small>{creator?<label>Status<select value={selected.ticket.status} onChange={e=>void run(async()=>{await api.request('/api/pilot/ticket_status',{method:'POST',body:{ticketId:selected.ticket.id,status:e.target.value}});await open(selected.ticket.id);await load();})}>{ticketStatuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label>:<p>{label(selected.ticket.status)}</p>}{selected.replies.map(r=><article className="pilot-reply" key={r.id}><small>{r.internal?'Internal development note':'Requester-visible reply'} · {new Date(r.created_at).toLocaleString()}</small><p>{r.body}</p></article>)}<form onSubmit={e=>{e.preventDefault();void run(async()=>{await api.request('/api/pilot/ticket_reply',{method:'POST',body:{ticketId:selected.ticket.id,body:reply,internal}});setReply('');await open(selected.ticket.id);});}}><label>Reply<textarea required maxLength={6000} value={reply} onChange={e=>setReply(e.target.value)}/></label>{creator?<label><input type="checkbox" checked={internal} onChange={e=>setInternal(e.target.checked)}/> Internal note</label>:null}<button disabled={busy}>Save reply</button></form>{creator?<details><summary>Approve a development task</summary><p>Write the authorized change and acceptance criteria. The ticket itself does not authorize code execution.</p><label>Development instructions<textarea value={instruction} maxLength={12000} onChange={e=>setInstruction(e.target.value)}/></label><button disabled={busy||!instruction.trim()} onClick={()=>void run(async()=>{await api.request('/api/pilot/job_create',{method:'POST',body:{ticketId:selected.ticket.id,instruction}});setMessage('Development task queued. Open Development to follow it.');})}>Approve and queue development</button></details>:null}</>:<p>Select a ticket to view its conversation.</p>}<p role="status">{message}</p></section></div>;
}
function DevelopmentWorkspace({api,previewMode}:{api:PilotApiClient;previewMode:boolean}){
 const [jobs,setJobs]=useState<DevelopmentJob[]>([]),[selectedId,setSelectedId]=useState(''),[message,setMessage]=useState(''),[prompt,setPrompt]=useState(''),[path,setPath]=useState(''),[content,setContent]=useState('');
 const load=useCallback(async()=>setJobs(await api.request('/api/pilot/jobs')),[api]);
 useEffect(()=>{const timer=setTimeout(()=>void load().catch(e=>setMessage(e.message)),0);const poll=setInterval(()=>void load().catch(e=>setMessage(e.message)),10000);return()=>{clearTimeout(timer);clearInterval(poll);};},[load]);
 const selected=jobs.find(j=>j.id===selectedId),result=selected?.result;
 const action=async(name:string,extra:Record<string,unknown>={})=>{try{await api.request(`/api/pilot/${name}`,{method:'POST',body:{jobId:selectedId,...extra}});await load();setMessage(name==='job_approve'?'Revision approved. Release remains a separate controlled deployment.':'Saved.');}catch(e){setMessage(e instanceof Error?e.message:'Action failed.');}};
 return <section><h2>Development workspace</h2><p>{previewMode?'Demo tickets cannot run Codex. Pair the authenticated pilot with your local worker to begin.':'Tasks run in isolated local checkouts. Your computer must be online.'}</p><label>Task<select value={selectedId} onChange={e=>{setSelectedId(e.target.value);setPath('');setContent('');}}><option value="">Select a task</option>{jobs.map(j=><option key={j.id} value={j.id}>{j.id.slice(0,8)} · {label(j.status)}</option>)}</select></label>{selected?<><p>{selected.instruction}</p><p>Status: {label(selected.status)} · Revision: {selected.revision||'Not ready'}</p><div className="pilot-columns"><section><h3>Conversation and follow-up</h3><pre>{result?.summary||'Waiting for worker output.'}</pre><label>Next instruction<textarea value={prompt} onChange={e=>setPrompt(e.target.value)}/></label><button disabled={!prompt.trim()||!['review','failed','approved'].includes(selected.status)} onClick={()=>void action('job_continue',{instruction:prompt})}>Continue task</button><h3>Project files</h3><label>File<select value={path} onChange={e=>{setPath(e.target.value);setContent(result?.files?.find(f=>f.path===e.target.value)?.content||'');}}><option value="">Select a file</option>{result?.files?.map(f=><option key={f.path}>{f.path}</option>)}</select></label><label>Editor<textarea className="pilot-code" value={content} onChange={e=>setContent(e.target.value)} disabled={!path}/></label><button disabled={!path||!['review','failed','approved'].includes(selected.status)} onClick={()=>void action('job_continue',{instruction:`Apply this reviewed file edit to ${path}, then rerun checks.\n${content}`})}>Queue edit and recheck</button></section><section><h3>Changes</h3><pre>{result?.diff||'No change comparison yet.'}</pre><h3>Checks</h3><pre>{result?.tests||'Not run'}</pre><h3>Preview</h3>{result?.previewUrl&&/^http:\/\/127\.0\.0\.1:\d+\//.test(result.previewUrl)?<iframe title="Isolated local preview" src={result.previewUrl} sandbox="allow-scripts"/>:<p>Preview unavailable until a local build succeeds.</p>}<h3>Release review</h3><button disabled={selected.status!=='review'||!result?.checksPassed||!selected.revision} onClick={()=>void action('job_approve',{revision:selected.revision})}>Approve this revision</button><button disabled={selected.status==='released'||selected.status==='cancelled'} onClick={()=>void action('job_cancel')}>Cancel task</button><p>Production deployment credentials are not available to the coding worker.</p></section></div></>:<p>Approve a ticket for development from Support to create a task.</p>}<p role="status">{message}</p></section>;
}
function AutomationPanel({api}:{api:PilotApiClient}){
 const [data,setData]=useState<{schedules:AutomationSchedule[];runs:AutomationRun[]}>({schedules:[],runs:[]}),[message,setMessage]=useState('');
 const load=useCallback(async()=>setData(await api.request('/api/pilot/automations')),[api]);
 useEffect(()=>{const timer=setTimeout(()=>void load().catch(e=>setMessage(e.message)),0);return()=>clearTimeout(timer);},[load]);
 const save=async(s:AutomationSchedule)=>{try{await api.request('/api/pilot/automation_save',{method:'POST',body:{id:s.id,enabled:s.enabled,localTime:s.local_time}});await load();}catch(e){setMessage(e instanceof Error?e.message:'Save failed.');}};
 return <section><h2>Scheduled operations</h2><p>America/Los_Angeles. Weekly: Monday. Monthly: first day. Annual: September 1. Local maintenance pauses while the computer is offline; hosted email continues independently.</p>{data.schedules.map(s=><article key={s.id} className="pilot-schedule"><strong>{label(s.cadence)}</strong><label>Time<input type="time" value={s.local_time} onChange={e=>setData(d=>({...d,schedules:d.schedules.map(v=>v.id===s.id?{...v,local_time:e.target.value}:v)}))}/></label><label><input type="checkbox" checked={s.enabled} onChange={e=>void save({...s,enabled:e.target.checked})}/> Enabled</label><button onClick={()=>void save(s)}>Save schedule</button><small>Last period: {s.last_period||'Not run'}</small></article>)}<h3>Run history</h3>{data.runs.length?data.runs.map(r=><article key={r.id}><strong>{r.schedule_id} · {r.period} · {r.status}</strong><ul>{r.findings.map((f,i)=><li key={i}>{f}</li>)}</ul></article>):<p>No runs recorded. Health and recovery are unverified.</p>}<p role="status">{message}</p></section>;
}
function HealthPanel({api}:{api:PilotApiClient}){
 const [checkedAt]=useState(()=>Date.now());
 const [data,setData]=useState<{worker:{last_seen:string;version:string}|null;samples:Array<{category:string;status:string;samples:number;duration_ms:number|null;last_seen:string}>;email:Record<string,number>}|null>(null),[message,setMessage]=useState('');
 useEffect(()=>{const timer=setTimeout(()=>void api.request<NonNullable<typeof data>>('/api/pilot/health').then(setData).catch(e=>setMessage(e.message)),0);return()=>clearTimeout(timer);},[api]);
 return <section><h2>Platform health</h2><div className="pilot-metrics"><article><strong>Local worker</strong><p>{data?.worker?(checkedAt-Date.parse(data.worker.last_seen)<180000?'Online':'Offline'):'Unknown · not paired'}</p><small>{data?.worker?.version}</small></article><article><strong>Backup recovery</strong><p>Unknown · verified restore evidence required</p></article><article><strong>SSO</strong><p>Awaiting IT metadata and validation</p></article></div><h3>Last 24 hours</h3>{data?.samples.length?<table><thead><tr><th>Service</th><th>Status</th><th>Samples</th><th>Average ms</th></tr></thead><tbody>{data.samples.map(s=><tr key={s.category+s.status}><td>{s.category}</td><td>{s.status}</td><td>{s.samples}</td><td>{s.duration_ms??'Unknown'}</td></tr>)}</tbody></table>:<p>No telemetry received. Performance is unknown.</p>}<h3>Email delivery</h3>{data&&Object.keys(data.email).length?<ul>{Object.entries(data.email).map(([status,n])=><li key={status}>{label(status)}: {n}</li>)}</ul>:<p>No delivery records.</p>}<p role="status">{message}</p></section>;
}
function VenueDirectory(){
 const [query,setQuery]=useState('');const filtered=venues.filter(v=>`${v.venue_name} ${v.venue_code} ${v.building}`.toLowerCase().includes(query.toLowerCase()));
 return <section><h2>Facilities directory</h2><p>Pilot booking requests: Summerlin only, pending external confirmation. Summerlin room details await verification. This partial Henderson catalog is reference-only.</p><label>Find a Henderson venue<input value={query} onChange={e=>setQuery(e.target.value)}/></label><p>{filtered.length} of {venues.length} source records</p><table><thead><tr><th>Source ID</th><th>Venue</th><th>Capacity</th><th>Details</th></tr></thead><tbody>{filtered.map(v=><tr key={v.venue_id}><td>{v.venue_code}</td><td>{v.venue_name}</td><td>{v.max_capacity>0?v.max_capacity:'Unverified'}</td><td>{v.location_detail}<br/>{v.amenities}<small>Source values retained; external booking authority.</small></td></tr>)}</tbody></table></section>;
}
