"use client";
import {useEffect,useState} from 'react';
import type {PilotApiClient} from './api-client';
type Person={id:string;name:string};
export function PilotStudentView({api,creator,previewMode}:{api:PilotApiClient;creator:boolean;previewMode:boolean}){
 const [people,setPeople]=useState<Person[]>([]),[directory,setDirectory]=useState<Person[]>([]),[student,setStudent]=useState(''),[staff,setStaff]=useState(''),[allowed,setAllowed]=useState(false),[rows,setRows]=useState<Array<{id:string;subject:string;status:string;recap:string|null;startsAt:string}>>([]),[message,setMessage]=useState('');
 useEffect(()=>{if(previewMode)return;const timer=setTimeout(()=>{void api.request<Person[]>('/api/pilot/student-view?action=list').then(setPeople).catch(e=>setMessage(e.message));if(creator)void api.request<{people:Person[]}>('/api/pilot/student-view?action=access_directory').then(v=>setDirectory(v.people)).catch(e=>setMessage(e.message));},0);return()=>clearTimeout(timer);},[api,creator,previewMode]);
 const read=async(id:string)=>{setStudent(id);setRows([]);if(!id)return;try{setRows(await api.request(`/api/pilot/student-view?action=read&studentId=${id}`));}catch(e){setMessage(e instanceof Error?e.message:'View unavailable.');}};
 return <section><h2>Student-facing support view</h2><p>Read-only. Published recaps only. Your own identity remains active and access is logged.</p>{previewMode?<p>Use the fictional student role in the demo selector to practice student workflows. This demo does not impersonate a real student.</p>:<><label>Assigned student<select value={student} onChange={e=>void read(e.target.value)}><option value="">Select a student</option>{people.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>{!people.length?<p>No student-facing assignments are available.</p>:null}{rows.map(r=><article key={r.id}><h3>{r.subject||'Advising visit'}</h3><small>{r.startsAt?new Date(r.startsAt).toLocaleString():''} · {r.status}</small><p>{r.recap||'No published recap.'}</p></article>)}{creator?<details><summary>Creator access override</summary><p>Grant or deny student-facing support for a specific staff/student pair. This does not grant private note access.</p><label>Staff<select value={staff} onChange={e=>setStaff(e.target.value)}><option value="">Select staff</option>{directory.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Student<select value={student} onChange={e=>setStudent(e.target.value)}><option value="">Select student</option>{directory.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label><input type="checkbox" checked={allowed} onChange={e=>setAllowed(e.target.checked)}/> Allow read-only student-facing support</label><button disabled={!staff||!student||staff===student} onClick={async()=>{try{await api.request('/api/pilot/student-view',{method:'POST',body:{action:'override',staffId:staff,studentId:student,allowed}});setMessage('Override saved and audited.');}catch(e){setMessage(e instanceof Error?e.message:'Override failed.');}}}>Save explicit override</button></details>:null}</>}<p role="status">{message}</p></section>;
}
