"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { PilotApiClient } from "./api-client";
import { campusDay, combinedCalendar, eventCsv, type FacilitiesNeed, type SharedEventExperience, type SharedEventPlan, type SharedEventWorkspace } from "./shared-event-model";
import { handoffDocx } from "./event-handoff-docx";
import { localTimeToUtc } from "./workspace-model";

const empty: SharedEventWorkspace = {events:[],occurrences:[],facilitiesRequests:[],evaluations:[],handoffs:[],oacaOverlay:[],possibleDuplicates:[]};
type Props = { api:PilotApiClient; experience:SharedEventExperience; canCreate:boolean; canReview?:boolean; previewMode:boolean; userId:string;
  studentView?:boolean; organizations?:Array<{id?:string;name:string}>; onBack?:()=>void };
const blank = {title:"",kind:"community",objective:"",audience:"",startsAt:"",endsAt:"",partner:"",accessibility:"",staffing:"",communications:"",estimatedCost:"",evaluationMeasures:"",location:"",roleDuties:"",recurrenceLabel:""};
const handoffBlank={roleDuties:"",eventHistory:"",metrics:"",analytics:"",openDecisions:"",nextActions:""};
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}
function localDate(value:string|null){if(!value)return "";return new Intl.DateTimeFormat("sv-SE",{timeZone:"America/Los_Angeles",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).format(new Date(value)).replace(" ","T");}

export function SharedEventCoordination({api,experience,canCreate,canReview=false,previewMode,userId,studentView=false,organizations=[],onBack}:Props){
  const [data,setData]=useState(empty); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  const [showOaca,setShowOaca]=useState(false);const [selected,setSelected]=useState("");const [editingId,setEditingId]=useState("");const [form,setForm]=useState(blank);
  const [organizationId,setOrganizationId]=useState(organizations[0]?.id||"");const [needs,setNeeds]=useState<FacilitiesNeed[]>([]);
  const [occurrences,setOccurrences]=useState<Array<{startsAt:string;endsAt:string}>>([]);
  const [evaluation,setEvaluation]=useState({registrations:"",attendance:"",estimatedCost:"",actualCost:"",goalsMet:"",partnerFeedback:"",coordination:"",keepNextTime:"",changeNextTime:"",purchaseNeeds:""});
  const [handoff,setHandoff]=useState(handoffBlank);const [successor,setSuccessor]=useState("");const [from,setFrom]=useState("");const [to,setTo]=useState("");const [kind,setKind]=useState("");const [status,setStatus]=useState("");const [query,setQuery]=useState("");const [dataCategory,setDataCategory]=useState<"all"|"metrics"|"facilities">("all");
  const load=useCallback(async()=>{try{setData(await api.request<SharedEventWorkspace>("/api/shared-events/workspace"));setMessage("");}catch(error){setMessage(error instanceof Error?error.message:"Events could not be loaded.");}},[api]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  const active=data.events.find((item)=>item.id===selected);
  const dates=useMemo(()=>active?data.occurrences.filter((item)=>item.eventId===active.id):[],[active,data.occurrences]);
  const published=combinedCalendar(data,showOaca);
  const filtered=data.events.filter((item)=>(!studentView||item.createdBy===userId)&&(!from||campusDay(item.startsAt)>=from)&&(!to||campusDay(item.startsAt)<=to)&&(!kind||item.kind===kind)&&(!status||item.status===status)&&(!query||item.title.toLowerCase().includes(query.toLowerCase())));
  const act=async(path:string,body:Record<string,unknown>,success:string)=>{setBusy(true);try{await api.request(path,{method:"POST",body});await load();setMessage(success);}catch(error){setMessage(error instanceof Error?error.message:"The action could not be completed.");}finally{setBusy(false);}};
  const save=async(event:React.FormEvent)=>{event.preventDefault();if(!form.startsAt){setMessage("Choose at least one date.");return;}
    try {const selectedDates=[{startsAt:form.startsAt,endsAt:form.endsAt},...occurrences];
      const utc=(value:string)=>localTimeToUtc(value,"America/Los_Angeles");
      await act("/api/shared-events/plan",{eventId:editingId||undefined,organizationId:organizationId||undefined,title:form.title,kind:form.kind,objective:form.objective,audience:form.audience,startsAt:utc(form.startsAt),endsAt:form.endsAt?utc(form.endsAt):null,
        recurrence:{label:form.recurrenceLabel},occurrences:selectedDates.map((item)=>({startsAt:utc(item.startsAt),endsAt:item.endsAt?utc(item.endsAt):null})),
        details:{partner:form.partner,accessibility:form.accessibility,staffing:form.staffing,communications:form.communications,estimatedCost:Number(form.estimatedCost)||0,evaluationMeasures:form.evaluationMeasures,location:form.location,roleDuties:form.roleDuties,facilities:needs}},"Event draft saved. Submit it when the details are ready.");
      setEditingId("");
    } catch(error) { setMessage(error instanceof Error?error.message:"Choose a valid campus date and time."); }
  };
  const exportCsv=async()=>{setBusy(true);try{let content:string;
    if(previewMode) content=eventCsv(filtered.filter((item)=>canReview||item.createdBy===userId),data.evaluations,data.facilitiesRequests,dataCategory);
    else {const search=new URLSearchParams({from,to,kind,status,name:query,data:dataCategory});const result=await api.download(`/api/shared-events/report?${search}`);content=await result.blob.text();}
    download(new Blob([content],{type:"text/csv;charset=utf-8"}),"compass-events.csv");setMessage("CSV report downloaded.");
  }catch(error){setMessage(error instanceof Error?error.message:"The report could not be prepared.");}finally{setBusy(false);}};
  const latestHandoff=active?data.handoffs.find((item)=>item.eventId===active.id):undefined;
  const createDocx=()=>{if(!active||!latestHandoff)return;const bytes=handoffDocx(active,latestHandoff);download(new Blob([new Uint8Array(bytes)],{type:"application/vnd.openxmlformats-officedocument.wordprocessingml.document"}),`compass-handoff-${active.id}.docx`);};
  const canOwn=active && active.ownerExperience===experience && active.createdBy===userId;
  const canCoordinate=active && active.ownerExperience===experience;
  const beginEdit=(item:SharedEventPlan)=>{setEditingId(item.id);setSelected(item.id);setForm({title:item.title,kind:item.kind,objective:item.objective,audience:item.audience,startsAt:localDate(item.startsAt),endsAt:localDate(item.endsAt),partner:item.details.partner||"",accessibility:item.details.accessibility||"",staffing:item.details.staffing||"",communications:item.details.communications||"",estimatedCost:String(item.details.estimatedCost||""),evaluationMeasures:item.details.evaluationMeasures||"",location:item.details.location||"",roleDuties:item.details.roleDuties||"",recurrenceLabel:item.recurrence.label||""});setNeeds(item.details.facilities||[]);setOccurrences(data.occurrences.filter((row)=>row.eventId===item.id).slice(1).map((row)=>({startsAt:localDate(row.startsAt),endsAt:localDate(row.endsAt)})));window.scrollTo({top:0,behavior:"smooth"});};
  return <section className="experience-panel shared-events">
    {onBack?<button className="workspace-back text-button" onClick={onBack}>← Back to workspace</button>:null}
    <div className="section-heading"><div><p className="kicker">Shared event coordination</p><h1>Plan once, coordinate together.</h1><p>Impact, OACA, and Facilities keep one event identity. Room and inventory needs remain pending until Facilities confirms them.</p></div></div>
    <div className="shared-events__calendar"><div className="section-heading"><h2>Calendar</h2><label><input type="checkbox" checked={showOaca} onChange={(event)=>setShowOaca(event.target.checked)}/> {experience==="genesis"?"Show published OACA events":"Show shared Impact events"}</label></div><div className="record-list">{published.map((item)=><article key={`${item.id}:${item.occurrenceId||item.startsAt}`}><strong>{item.title}</strong><span>{new Date(item.startsAt).toLocaleString("en-US",{timeZone:"America/Los_Angeles",dateStyle:"medium",timeStyle:"short"})} · {item.source==="genesis"?"Impact Studio":"OACA"}</span></article>)}{!published.length?<p>No published events in this view.</p>:null}</div></div>
    {canCreate?<details className="event-admin-card" open={editingId?true:undefined}><summary>{editingId?"Edit event request":"Create an event request"}</summary><form className="experience-form" onSubmit={(event)=>void save(event)}>
      {experience==="genesis"&&organizations.length?<label><span>Organization</span><select required value={organizationId} onChange={(event)=>setOrganizationId(event.target.value)}>{organizations.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>:null}
      <div className="form-row"><label><span>Event name</span><input required minLength={3} value={form.title} onChange={(event)=>setForm({...form,title:event.target.value})}/></label><label><span>Type</span><select value={form.kind} onChange={(event)=>setForm({...form,kind:event.target.value})}><option value="community">Community</option><option value="academic">Academic</option><option value="career">Career</option><option value="campus">Campus</option></select></label></div>
      <label><span>Purpose and expected outcome</span><textarea required value={form.objective} onChange={(event)=>setForm({...form,objective:event.target.value})}/></label>
      <label><span>Audience</span><input required value={form.audience} onChange={(event)=>setForm({...form,audience:event.target.value})}/></label>
      <div className="form-row"><label><span>Start</span><input type="datetime-local" required value={form.startsAt} onChange={(event)=>setForm({...form,startsAt:event.target.value})}/></label><label><span>End</span><input type="datetime-local" value={form.endsAt} onChange={(event)=>setForm({...form,endsAt:event.target.value})}/></label></div>
      <label><span>Series name or cadence, if recurring</span><input value={form.recurrenceLabel} onChange={(event)=>setForm({...form,recurrenceLabel:event.target.value})}/></label>
      {occurrences.map((item,index)=><div className="form-row" key={index}><label><span>Additional date {index+1}</span><input type="datetime-local" value={item.startsAt} onChange={(event)=>setOccurrences(occurrences.map((row,i)=>i===index?{...row,startsAt:event.target.value}:row))}/></label><label><span>End</span><input type="datetime-local" value={item.endsAt} onChange={(event)=>setOccurrences(occurrences.map((row,i)=>i===index?{...row,endsAt:event.target.value}:row))}/></label><button type="button" className="text-button" onClick={()=>setOccurrences(occurrences.filter((_,i)=>i!==index))}>Remove date</button></div>)}
      <button type="button" className="secondary-button" onClick={()=>setOccurrences([...occurrences,{startsAt:"",endsAt:""}])}>Add another date</button>
      <div className="form-row"><label><span>Community partner</span><input value={form.partner} onChange={(event)=>setForm({...form,partner:event.target.value})}/></label><label><span>Proposed Summerlin location</span><input value={form.location} onChange={(event)=>setForm({...form,location:event.target.value})}/></label></div>
      <label><span>Accessibility</span><textarea value={form.accessibility} onChange={(event)=>setForm({...form,accessibility:event.target.value})}/></label>
      <label><span>Staffing and safety</span><textarea value={form.staffing} onChange={(event)=>setForm({...form,staffing:event.target.value})}/></label>
      <label><span>Communications</span><textarea value={form.communications} onChange={(event)=>setForm({...form,communications:event.target.value})}/></label>
      <div className="form-row"><label><span>Estimated budget</span><input type="number" min="0" step="0.01" value={form.estimatedCost} onChange={(event)=>setForm({...form,estimatedCost:event.target.value})}/></label><label><span>Evaluation measures</span><input value={form.evaluationMeasures} onChange={(event)=>setForm({...form,evaluationMeasures:event.target.value})}/></label></div>
      <label><span>Role duties for eventual handoff</span><textarea value={form.roleDuties} onChange={(event)=>setForm({...form,roleDuties:event.target.value})}/></label>
      <fieldset><legend>Facilities needs</legend>{needs.map((need,index)=><div className="form-row" key={index}><select aria-label={`Facilities need ${index+1}`} value={need.kind} onChange={(event)=>setNeeds(needs.map((row,i)=>i===index?{...row,kind:event.target.value as FacilitiesNeed["kind"]}:row))}><option value="room">Room request</option><option value="setup">Setup</option><option value="inventory">Inventory</option></select><input aria-label={`Facilities description ${index+1}`} placeholder="Need or item name" value={need.description} onChange={(event)=>setNeeds(needs.map((row,i)=>i===index?{...row,description:event.target.value}:row))}/>{need.kind==="inventory"?<input aria-label={`Quantity ${index+1}`} type="number" min="1" value={need.quantity||1} onChange={(event)=>setNeeds(needs.map((row,i)=>i===index?{...row,quantity:Number(event.target.value),itemKey:row.description}:row))}/>:null}<button type="button" className="text-button" onClick={()=>setNeeds(needs.filter((_,i)=>i!==index))}>Remove</button></div>)}<button type="button" className="secondary-button" onClick={()=>setNeeds([...needs,{kind:"room",description:""}])}>Add Facilities need</button><small>Inventory is a reusable series template. Facilities confirms each event date separately.</small></fieldset>
      <button className="primary-button" disabled={busy}>{busy?"Saving…":editingId?"Save request changes":"Save event draft"}</button>
    </form></details>:null}
    {!studentView?<div className="shared-events__reports"><h2>Events and reports</h2><div className="form-row"><label><span>From</span><input type="date" value={from} onChange={(event)=>setFrom(event.target.value)}/></label><label><span>Through</span><input type="date" value={to} onChange={(event)=>setTo(event.target.value)}/></label><label><span>Type</span><select value={kind} onChange={(event)=>setKind(event.target.value)}><option value="">All types</option>{[...new Set(data.events.map((item)=>item.kind))].map((item)=><option key={item}>{item}</option>)}</select></label><label><span>Status</span><select value={status} onChange={(event)=>setStatus(event.target.value)}><option value="">All statuses</option>{[...new Set(data.events.map((item)=>item.status))].map((item)=><option key={item} value={item}>{item.replaceAll("_"," ")}</option>)}</select></label><label><span>Event name</span><input type="search" value={query} onChange={(event)=>setQuery(event.target.value)}/></label><label><span>Data</span><select value={dataCategory} onChange={(event)=>setDataCategory(event.target.value as typeof dataCategory)}><option value="all">All coordination data</option><option value="metrics">Attendance and cost</option><option value="facilities">Facilities status</option></select></label></div><button className="secondary-button" disabled={busy} onClick={()=>void exportCsv()}>Download selected CSV</button></div>:null}
    {!studentView&&data.possibleDuplicates.length?<aside className="configuration-banner"><strong>Possible repeated events</strong><p>{data.possibleDuplicates.length} title and date matches need a coordinator review. They were not merged automatically.</p></aside>:null}
    {!studentView||filtered.length?<div className="record-list">{filtered.map((item)=><article key={item.id}><span className="status-chip">{item.status.replaceAll("_"," ")}</span><h2>{item.title}</h2><p>{item.startsAt?new Date(item.startsAt).toLocaleString("en-US",{timeZone:"America/Los_Angeles"}):"Date pending"} · {item.kind}</p><button className="secondary-button" onClick={()=>setSelected(selected===item.id?"":item.id)}>{selected===item.id?(studentView?"Close my request":"Close coordination"):(studentView?"Open my request":"Open coordination")}</button></article>)}{!filtered.length?<p>No events match these filters.</p>:null}</div>:null}
    {active?<section className="event-admin-card shared-events__detail"><h2>{active.title}</h2><p>{active.objective}</p><p>Event identity: {active.id}</p><p>Facilities: {data.facilitiesRequests.filter((item)=>item.eventId===active.id).map((item)=>`${item.requestKind} ${item.status}`).join(" · ")||"No requests"}</p>
      {canCreate && canCoordinate && (["draft","requested"].includes(active.status)||(experience==="oaca"&&active.status==="published"))?<button className="secondary-button" onClick={()=>beginEdit(active)}>Edit coordination details</button>:null}
      {canOwn && active.status==="draft"?<button className="primary-button" disabled={busy} onClick={()=>void act("/api/shared-events/submit",{eventId:active.id},"Request submitted; Facilities needs are pending confirmation.")}>Submit event request</button>:null}
      {canReview&&experience==="genesis"&&active.status==="requested"?<button className="secondary-button" disabled={busy} onClick={()=>void act("/api/shared-events/review",{eventId:active.id,reviewKind:"mentor",decision:"approved"},"Mentor review recorded.")}>Mentor approve</button>:null}
      {canReview&&experience==="genesis"&&active.status==="mentor_approved"?<button className="primary-button" disabled={busy} onClick={()=>void act("/api/shared-events/review",{eventId:active.id,reviewKind:"liaison",decision:"approved"},"Liaison approval recorded.")}>Liaison approve</button>:null}
      {canCreate&&experience==="oaca"&&canCoordinate&&(canOwn||canReview)&&active.status==="requested"?<button className="primary-button" disabled={busy} onClick={()=>void act("/api/shared-events/publish",{eventId:active.id},"Event published to the shared calendar.")}>Publish event</button>:null}
      <h3>Event dates and evaluation</h3>{dates.map((item)=><div key={item.id}><p>{new Date(item.startsAt).toLocaleString("en-US",{timeZone:"America/Los_Angeles"})} · {item.status}</p>{!data.evaluations.some((row)=>row.occurrenceId===item.id)&&canOwn?<details><summary>Complete post-event evaluation</summary><div className="experience-form"><div className="form-row">{(["registrations","attendance","estimatedCost","actualCost"] as const).map((field)=><label key={field}><span>{field.replace(/([A-Z])/g," $1")}</span><input type="number" min="0" step={field.includes("Cost")?"0.01":"1"} value={evaluation[field]} onChange={(event)=>setEvaluation({...evaluation,[field]:event.target.value})}/></label>)}</div>{(["goalsMet","partnerFeedback","coordination","keepNextTime","changeNextTime","purchaseNeeds"] as const).map((field)=><label key={field}><span>{field.replace(/([A-Z])/g," $1")}</span><textarea value={evaluation[field]} onChange={(event)=>setEvaluation({...evaluation,[field]:event.target.value})}/></label>)}<button className="primary-button" disabled={busy} onClick={()=>void act("/api/shared-events/evaluation",{eventId:active.id,occurrenceId:item.id,...evaluation},"Evaluation saved.")}>Save evaluation</button></div></details>:null}{data.evaluations.filter((row)=>row.occurrenceId===item.id).map((row)=><p key={row.occurrenceId}>{row.attendance} attended · ${row.actualCost.toFixed(2)} actual cost · {row.keepNextTime}</p>)}</div>)}
      {canOwn?<details><summary>Prepare role and event handoff</summary><p>Complete the document before entering a successor email.</p><div className="experience-form">{(Object.keys(handoffBlank) as Array<keyof typeof handoffBlank>).map((field)=><label key={field}><span>{field.replace(/([A-Z])/g," $1")}</span><textarea required value={handoff[field]} onChange={(event)=>setHandoff({...handoff,[field]:event.target.value})}/></label>)}<button className="primary-button" disabled={busy||Object.values(handoff).some((value)=>!value.trim())} onClick={()=>void act("/api/shared-events/handoff",{eventId:active.id,document:handoff},"Handoff completed. You can now enter the successor email.")}>Complete handoff document</button></div></details>:null}
      {latestHandoff?<div className="workspace-actions"><button className="secondary-button" onClick={createDocx}>Download editable Word document</button>{latestHandoff.status==="complete"?<label><span>Successor email</span><input type="email" value={successor} onChange={(event)=>setSuccessor(event.target.value)}/><button className="primary-button" disabled={busy||!successor} onClick={()=>void act("/api/shared-events/handoff/offer",{eventId:active.id,handoffId:latestHandoff.id,successorEmail:successor},"Handoff offered to the successor.")}>Offer handoff</button></label>:<span>{latestHandoff.status.replaceAll("_"," ")}</span>}</div>:null}
    </section>:null}
    <p role="status" className="form-message">{message}</p>
  </section>;
}
