"use client";

import { useCallback, useEffect, useState } from "react";
import type { PilotApiClient } from "./api-client";
import { parseRosterText } from "./creator-roster-import";

type RosterEntry = { id: string; email: string; display_name: string; role_title?: string | null; roles: string[]; workspace_roles: Record<string,string[]>; view_bundle?: Record<string,unknown>; status: string };
type PendingIdentity = { auth_user_id: string; email: string; display_name: string | null; status: string };
type Draft = { email: string; displayName: string; roleTitle: string; roles: string[]; workspaceRoles: Record<string,string[]>; viewBundle: Record<string,unknown> };
const blank = (): Draft => ({ email: "", displayName: "", roleTitle: "", roles: ["advisor"], workspaceRoles: { oaca: ["advisor"], facilities: ["requester"] }, viewBundle: { capabilities: ["oaca.advisor.academic"] } });
const workspaceOptions: Record<string,string[]> = { oaca: ["advisor","student","staff","administrator"], pathway: ["advisor","student","faculty","staff","administrator","principal_investigator"], genesis: ["student","staff","administrator"], facilities: ["requester","staff","administrator"] };
const workspaceNames: Record<string,string> = { oaca:"Compass Advising / Tutoring", pathway:"Navigate the Pathway", genesis:"Impact Studio", facilities:"Facilities" };
const views: Record<string,string> = { "oaca.advisor.academic":"Academic Advisor", "oaca.advisor.career":"Career Advisor", "oaca.view.student":"Student view", "oaca.view.peer_tutor":"Peer Tutor", "oaca.tutoring.manage":"Tutoring Manager" };
const toggle = (values:string[], value:string, checked:boolean) => checked ? [...new Set([...values,value])] : values.filter((item)=>item!==value);
const label = (value:string) => value.replaceAll("_"," ").replace(/^./,c=>c.toUpperCase());

export function StaffSsoAccess({api}:{api:PilotApiClient}) {
  const [roster,setRoster]=useState<RosterEntry[]>([]), [pending,setPending]=useState<PendingIdentity[]>([]);
  const [draft,setDraft]=useState<Draft>(blank), [editingId,setEditingId]=useState<string|null>(null);
  const [message,setMessage]=useState(""), [busy,setBusy]=useState(false), [bulkText,setBulkText]=useState("");
  const [bulkPreview,setBulkPreview]=useState<{text:string;count:number;diff:Array<{email:string;action:string}>}|null>(null);
  const load=useCallback(async()=>{ const value=await api.request<{roster:RosterEntry[];pending:PendingIdentity[]}>("/api/admin/sso-access");setRoster(value.roster);setPending(value.pending); },[api]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load().catch(error=>setMessage(error.message)),0);return()=>window.clearTimeout(timer);},[load]);
  const run=async(task:()=>Promise<void>)=>{setBusy(true);setMessage("");try{await task();}catch(error){setMessage(error instanceof Error?error.message:"The request could not be completed.");}finally{setBusy(false);}};
  const reset=()=>{setEditingId(null);setDraft(blank());};
  const edit=(entry:RosterEntry)=>{setEditingId(entry.id);setDraft({email:entry.email,displayName:entry.display_name,roleTitle:entry.role_title||"",roles:[...entry.roles],workspaceRoles:structuredClone(entry.workspace_roles),viewBundle:structuredClone(entry.view_bundle||{})});};
  const save=async()=>{await api.request(editingId?`/api/admin/sso-access/roster/${editingId}`:"/api/admin/sso-access/roster",{method:editingId?"PATCH":"POST",body:{...draft,email:draft.email.trim().toLowerCase()}});await load();reset();setMessage("Roster saved. Access requires an approved match to the person's Roseman identity.");};
  const caps=Array.isArray(draft.viewBundle.capabilities)?draft.viewBundle.capabilities.filter((value):value is string=>typeof value==="string"):[];
  return <section className="production-card production-card--wide"><p className="kicker">Roseman SSO roster</p><h2>Manage Compass staff access</h2><p>Select the workspaces and views this person needs. Only an approved, matching Roseman identity can use them.</p>
    <details><summary>Bulk roster import</summary><label>Roster table<textarea rows={5} value={bulkText} onChange={event=>{setBulkText(event.target.value);setBulkPreview(null);}} placeholder={"Name\tEmail\tRole(s)\tPermissions/Views"}/></label><button type="button" className="secondary-button" disabled={busy||!bulkText.trim()} onClick={()=>void run(async()=>{const result=await api.request<{count:number;diff:Array<{email:string;action:string}>}>("/api/admin/sso-access/roster/bulk",{method:"POST",body:{rows:parseRosterText(bulkText),commit:false}});setBulkPreview({...result,text:bulkText});})}>Preview import</button>{bulkPreview?<><ul>{bulkPreview.diff.map(item=><li key={item.email}>{item.email}: {item.action}</li>)}</ul><button type="button" className="primary-button" disabled={busy||bulkPreview.text!==bulkText} onClick={()=>void run(async()=>{await api.request("/api/admin/sso-access/roster/bulk",{method:"POST",body:{rows:parseRosterText(bulkPreview.text),commit:true}});setBulkText("");setBulkPreview(null);await load();setMessage("Approved roster changes saved.");})}>Apply {bulkPreview.count} reviewed entries</button></>:null}</details>
    <div className="identity-manager-grid"><form className="workspace-form" onSubmit={event=>{event.preventDefault();void run(save);}}><h3>{editingId?"Edit approved staff":"Add approved staff"}</h3>
      <label>Roseman email<input required type="email" pattern=".+@roseman\.edu" value={draft.email} onChange={event=>setDraft({...draft,email:event.target.value.toLowerCase()})}/></label>
      <label>Display name<input required maxLength={160} value={draft.displayName} onChange={event=>setDraft({...draft,displayName:event.target.value})}/></label>
      <label>Role title<input maxLength={160} value={draft.roleTitle} onChange={event=>setDraft({...draft,roleTitle:event.target.value})}/></label>
      <fieldset><legend>Broader staff roles</legend>{["advisor","administrator","faculty","staff","principal_investigator"].map(role=><label key={role}><input type="checkbox" checked={draft.roles.includes(role)} onChange={event=>setDraft({...draft,roles:toggle(draft.roles,role,event.target.checked)})}/>{label(role)}</label>)}{draft.roles.includes("creator")?<p>Creator assignment is preserved. Ownership transfer uses the protected Creator controls.</p>:null}</fieldset>
      {Object.entries(workspaceOptions).map(([workspace,roles])=><fieldset key={workspace}><legend>{workspaceNames[workspace]} views</legend>{roles.map(role=><label key={role}><input type="checkbox" checked={(draft.workspaceRoles[workspace]||[]).includes(role)} onChange={event=>setDraft({...draft,workspaceRoles:{...draft.workspaceRoles,[workspace]:toggle(draft.workspaceRoles[workspace]||[],role,event.target.checked)}})}/>{label(role)}</label>)}{draft.workspaceRoles[workspace]?.includes("creator")?<small>Creator access is assigned.</small>:null}</fieldset>)}
      <fieldset><legend>Compass advising and tutoring views</legend>{Object.entries(views).map(([value,name])=><label key={value}><input type="checkbox" checked={caps.includes(value)} onChange={event=>setDraft({...draft,viewBundle:{...draft.viewBundle,capabilities:toggle(caps,value,event.target.checked)}})}/>{name}</label>)}</fieldset>
      <button className="primary-button" disabled={busy}>{busy?"Saving…":editingId?"Save roster changes":"Save approved roster entry"}</button>{editingId?<button type="button" className="secondary-button" onClick={reset}>Cancel edit</button>:null}
    </form><section><h3>Pending Roseman identities</h3>{pending.filter(item=>item.status==="pending").map(identity=>{const matches=roster.filter(entry=>entry.status==="approved"&&entry.email===identity.email);return <article className="privacy-note" key={identity.auth_user_id}><strong>{identity.display_name||identity.email}</strong><p>{identity.email}</p><button type="button" className="primary-button" disabled={busy||matches.length!==1} onClick={()=>void run(async()=>{await api.request("/api/admin/sso-access/approve",{method:"POST",body:{pendingUserId:identity.auth_user_id,rosterEntryId:matches[0].id}});await load();setMessage("Roseman identity matched to the approved roster.");})}>Approve exact roster match</button>{matches.length!==1?<p>Exactly one approved roster row must match this email.</p>:null}</article>;})}{!pending.some(item=>item.status==="pending")?<p>No identities are awaiting review.</p>:null}</section></div>
    <p className="form-message" role="status">{message}</p><div className="access-log-table-wrap"><table className="access-log-table"><thead><tr><th>Person</th><th>Title</th><th>Assigned views</th><th>Status</th><th>Actions</th></tr></thead><tbody>{roster.map(entry=><tr key={entry.id}><td>{entry.display_name}<br/><small>{entry.email}</small></td><td>{entry.role_title||"—"}</td><td>{Object.entries(entry.workspace_roles).filter(([,roles])=>roles.length).map(([workspace,roles])=><div key={workspace}>{workspaceNames[workspace]||workspace}: {roles.map(label).join(", ")}</div>)}</td><td>{entry.status}</td><td><button type="button" disabled={busy||entry.status!=="approved"} onClick={()=>edit(entry)}>Edit</button><button type="button" disabled={busy||entry.status!=="approved"} onClick={()=>{if(window.confirm(`Revoke Compass access for ${entry.email}?`))void run(async()=>{await api.request(`/api/admin/sso-access/roster/${entry.id}`,{method:"DELETE",body:{}});await load();setMessage("Roster access revoked.");});}}>Revoke</button></td></tr>)}</tbody></table></div>
  </section>;
}
