// Fictional demonstration content only. These histories never seed production data.
type Visit = [service: "academic" | "career", subject: string, progress: string, guidance: string, action: string, followUp: string];
type Story = { id: string; name: string; advisor: string; concern: string; visits: Visit[] };

const stories: Story[] = [
  {
    id: "student-1", name: "Taylor Morgan", advisor: "Bucket L. Manyweather, Ph.D.",
    concern: "Taylor wants a sustainable Foundations study routine that leaves room for early career exploration without extending every study day into the evening. The plan needs to accommodate variable class days and optional campus activities.",
    visits: [
      ["academic", "Mapping the weekly workload", "At this initial visit, Taylor brought a calendar showing repeated lecture review and little time reserved for applying concepts.", "We compared fixed commitments with flexible study time and identified where rewriting material was displacing active practice.", "Track two ordinary study days and mark which activities require recall without looking at a source.", "Bring the activity log so we can choose one change that fits the actual week."],
      ["academic", "Starting a retrieval routine", "Taylor's activity log showed that review expanded to fill most available time; a short closed-book exercise felt useful but uncomfortable.", "We practiced starting with a question, explaining an answer aloud, and reviewing only the gap identified by that attempt.", "Try a brief question set before lecture review on three days and record one useful correction each day.", "Review which corrections persisted and whether the new sequence was feasible on longer class days."],
      ["career", "Making space for exploration", "Taylor completed the three practice attempts and wants to explore specialties without adding another large project to the weekly plan.", "We discussed low-commitment ways to learn about daily clinical work and distinguished curiosity from making an early specialty decision.", "Choose one specialty profile and write two questions about the clinician's typical work and learning environment.", "Revisit those questions after one introductory conversation and compare the time required with the study plan."],
      ["academic", "Adjusting after a busy week", "Taylor used the question-first sequence on two days, but a longer review assignment crowded out the third planned attempt.", "We treated the missed block as scheduling information and shortened the minimum practice task rather than expanding the evening workload.", "Protect two short practice blocks and use a five-minute recall exercise when a full block is unavailable.", "Bring examples from both the full and shortened routines so we can compare what each revealed."],
      ["career", "Turning an interview into questions", "Taylor read the selected profile and had an introductory conversation; the range of tasks was broader than expected from the profile alone.", "We separated observations from assumptions and explored which questions would be useful to ask someone in a different practice setting.", "Write a brief reflection and identify a second setting that could offer a contrasting view of the same specialty.", "Discuss whether another conversation adds useful information before committing time to it."],
      ["academic", "Keeping the plan workable", "Taylor brought examples from both practice routines and reported that the shorter version made restarting easier after an interrupted study day.", "We reviewed how to reserve practice time before optional review and planned to check the calendar again as coursework changes.", "Keep two protected practice blocks, record interruptions, and bring the updated weekly calendar to the next scheduled check-in.", "At the upcoming weekly-planning visit, check whether review is again crowding out retrieval practice."],
    ],
  },
  {
    id: "student-2", name: "Riley Thompson", advisor: "Bucket L. Manyweather, Ph.D.",
    concern: "Riley wants practice questions to support understanding rather than become a count to finish, particularly when explanations introduce several unfamiliar concepts at once. Explaining a correction independently is the student's chosen sign of progress.",
    visits: [
      ["academic", "Understanding question-review habits", "At the initial visit, Riley described finishing question sets quickly and copying explanations without returning to the reasoning behind missed items.", "We walked through one sample explanation and separated a knowledge gap from a misread prompt and an unsupported inference.", "Review a small set slowly and label the reason for each correction using those three categories.", "Bring two annotated examples to see whether the categories help identify a useful study priority."],
      ["academic", "Building a useful error log", "Riley's two examples showed different problems: one missing concept and one answer chosen before reading the final sentence carefully.", "We designed a brief error log that records the reasoning change and a next attempt instead of copying the full explanation.", "Use the log for three review sessions and write a new explanation from memory the following day.", "Check which entries lead to a clearer explanation and which need a tutor's help."],
      ["career", "Exploring teaching interests", "Riley noticed enjoyment in explaining corrected answers to a classmate and asked whether that interest connects to future clinical roles.", "We discussed teaching as an activity present across specialties and considered questions about supervision, patient education, and team learning.", "Read two clinician profiles and note how each describes teaching during ordinary clinical work.", "Compare the examples without using one enjoyable study activity to narrow specialty options prematurely."],
      ["academic", "Preparing focused tutoring questions", "Riley could explain several logged corrections the next day, but two concepts remained unclear even after another review of the source material.", "We converted those uncertainties into focused tutoring questions and practiced showing the attempted reasoning before asking for an explanation.", "Bring two attempted explanations to peer tutoring and revise the corresponding log entries after the session.", "Review what changed after tutoring and decide whether the same preparation method is worth repeating."],
      ["career", "Comparing ways clinicians teach", "Riley compared the two profiles and noticed differences between bedside teaching and longer patient-education conversations, with interest in both.", "We discussed how practice setting can shape those opportunities and drafted a neutral question for an informational conversation.", "Ask a clinician how teaching fits into a typical week and record one example that challenges an assumption.", "Return to the reflection after the conversation and identify what remains unknown."],
      ["academic", "Reviewing the revised study plan", "Riley reported that prepared questions made tutoring more focused, though reviewing every error-log entry in one sitting became difficult to sustain.", "We grouped entries by recurring reasoning issue and selected a smaller review rotation that fits around the current class schedule.", "Rotate through two recurring issues this week and bring the log to the pending study-plan appointment.", "At the next visit, assess whether the smaller rotation supports explanation and leaves time for new material."],
    ],
  },
  {
    id: "student-3", name: "Cameron Ellis", advisor: "Michael O'Leary, M.Ed.",
    concern: "Cameron is balancing Foundations coursework with broad specialty curiosity and wants a way to compare experiences without feeling required to choose a career direction immediately. Available time remains an explicit part of each exploration decision.",
    visits: [
      ["academic", "Balancing coursework and exploration", "At the first visit, Cameron described signing up for several optional activities while leaving study tasks to whatever time remained afterward.", "We mapped fixed coursework commitments and discussed reserving a realistic study baseline before selecting optional activities for the month.", "Choose one exploration activity and draft a weekly calendar with explicit preparation and recovery time.", "Bring the calendar and describe whether the chosen activity displaced essential coursework preparation."],
      ["career", "Defining exploration questions", "Cameron's calendar supported one activity, but the student found that broad specialty descriptions did not answer questions about everyday clinical work.", "We developed comparison prompts about patient relationships, pace, collaboration, and the types of problems clinicians spend time solving.", "Use the same four prompts while reading two contrasting specialty profiles and leave uncertain answers blank.", "Review the unanswered prompts to decide what an informational conversation could clarify."],
      ["academic", "Recovering time after an activity", "Cameron attended the selected activity and enjoyed it, but preparation for the following morning had been underestimated in the original calendar.", "We adjusted the activity-day schedule and discussed choosing a smaller preparation target instead of relying on a late-night catch-up session.", "Add preparation time before the next optional event and test a shorter review routine afterward.", "Check whether this adjustment makes exploration compatible with the student's existing academic commitments."],
      ["career", "Comparing observations across settings", "Cameron completed the profile comparison and found that continuity of patient relationships mattered more than the specialty names initially suggested.", "We distinguished an emerging preference from a fixed conclusion and considered how different settings within one specialty might vary.", "Draft two questions about continuity and ask them during an introductory conversation with a clinician.", "Compare the clinician's examples with the profiles and record any disagreement rather than smoothing it over."],
      ["academic", "Keeping optional commitments bounded", "Cameron used the earlier preparation block successfully once, then received invitations to additional activities that would exceed the available weekly time.", "We reviewed the calendar and practiced selecting an activity based on a specific unanswered question rather than attending everything offered.", "Keep one activity on the calendar and defer other invitations until the current academic block is reviewed.", "Bring the revised calendar if workload changes and identify which commitment would be adjusted first."],
      ["career", "Preparing for CiM reflection", "Cameron's conversation added a different view of continuity and confirmed that comparing settings may be more informative than ranking specialty labels.", "We introduced reflection prompts about interests and work preferences, explaining that a structured inventory is one input to exploration.", "Review the CiM reflection prompts and bring two specialty questions to the scheduled career advising visit.", "Use the next CiM visit to connect reflection results with observations and plan another bounded exploration step."],
    ],
  },
  {
    id: "student-4", name: "Alexis Nguyen", advisor: "Cameron Mastin, M.Ed.",
    concern: "Alexis is adjusting to the pace of the first year and wants a repeatable way to prepare for class, ask questions, and find support when unfamiliar routines accumulate.",
    visits: [
      ["academic", "Establishing a first-year routine", "At the initial meeting, Alexis described treating every reading as equally urgent and arriving at class unsure which questions to ask.", "We separated required preparation from optional enrichment and practiced turning a learning objective into one question to carry into class.", "Prepare one question for each of the next three class sessions and note where it was answered.", "Review the question list and identify which preparation steps supported participation rather than adding unnecessary work."],
      ["academic", "Finding a manageable preparation level", "Alexis prepared questions for three sessions and found two answers during class, while one question remained too broad to discuss efficiently.", "We revised the broad question into a specific point of confusion and discussed a time limit for initial preparation.", "Use a short preparation limit and take one unresolved, specific question to an instructor's office hours.", "Discuss the office-hours experience and whether the preparation limit leaves enough time for consolidation."],
      ["career", "Learning about paths through medicine", "Alexis felt more comfortable asking an academic question and wanted similar guidance for learning about careers without knowing many specialty names.", "We discussed starting with the kinds of work that spark curiosity and using early exploration to learn vocabulary and ask better questions.", "Choose an introductory career event and write two questions about the speaker's path and daily responsibilities.", "Bring one observation from the event and one question that still needs a clearer explanation."],
      ["academic", "Following up after office hours", "Alexis attended office hours and clarified the original question, but noted hesitation about returning before fully understanding a new topic.", "We discussed bringing an attempted explanation as preparation and normalized using office hours to resolve uncertainty during learning.", "Write a short attempted explanation for one current topic and identify the exact step that needs feedback.", "Review whether this approach makes it easier to seek help early in the next block."],
      ["career", "Reflecting on a first career event", "Alexis attended the event and was surprised by the variety of work within one physician's week, especially collaboration outside direct patient visits.", "We connected that observation to the original questions and discussed why one speaker's experience does not represent an entire field.", "Save a short reflection and choose a contrasting future event only when the coursework calendar allows it.", "Revisit the reflection later in the year to see which questions have become more specific."],
      ["academic", "Preparing for the next block", "Alexis brought an attempted explanation to a second office-hours visit and reported that asking earlier reduced the amount of unresolved material carried forward.", "We reviewed the preparation routine and identified the minimum steps to retain when the next block introduces a different schedule.", "Keep the preparation limit, a daily question list, and one weekly check for unresolved concepts.", "At the next advising check-in, compare the routine with the new block's demands and adjust one element if needed."],
    ],
  },
  {
    id: "student-5", name: "Avery Johnson", advisor: "Bucket L. Manyweather, Ph.D.",
    concern: "Avery wants to manage coursework alongside recurring outside commitments and needs a study plan that can absorb schedule changes without repeatedly relying on weekend catch-up. Reliable study windows are the starting point for this plan.",
    visits: [
      ["academic", "Mapping fixed commitments", "At the first meeting, Avery showed a full weekly calendar but had not included travel time or transitions between outside commitments and study.", "We identified fixed commitments and realistic transition time, then located smaller study windows that were actually available.", "Track the start and end of three study periods and note interruptions or delayed starts.", "Compare the observed windows with the calendar before choosing the size of future study blocks."],
      ["academic", "Building a flexible weekly plan", "Avery's log showed that two planned blocks consistently started late, while a shorter morning period was more reliable than expected.", "We moved demanding work into the reliable window and designed a smaller fallback task for days when another commitment runs over.", "Test the revised morning block twice and use a short recall task during one interrupted period.", "Review which task sizes fit the real schedule and whether the weekend catch-up list becomes more manageable."],
      ["career", "Choosing feasible exploration", "Avery tried both task sizes and wanted to include career exploration but was concerned that another scheduled event would create avoidable conflicts.", "We compared asynchronous profiles with live events and discussed choosing an activity for a specific question rather than its visibility.", "Read one career profile during a flexible window and identify a question about the work setting.", "Decide whether that question warrants a conversation and how to fit it into the next two weeks."],
      ["academic", "Responding to a disrupted week", "Avery used the fallback task during an unexpected schedule change but still moved several unfinished review activities to the weekend.", "We prioritized the review list by current learning needs and distinguished essential follow-up from optional repetition that could be dropped.", "Choose two essential review tasks, remove one redundant task, and reserve a small buffer before the weekend.", "Check whether the buffer absorbs ordinary interruptions without adding more total study time."],
      ["career", "Preparing a focused conversation", "Avery's profile raised a question about team roles, and the student identified a short conversation opportunity that fits an existing campus visit.", "We drafted a focused opening question and discussed recording concrete examples instead of trying to collect a complete specialty overview.", "Ask about one typical team interaction and write a brief reflection on what the example clarified.", "Review the reflection before selecting another activity so the next step addresses a different question."],
      ["academic", "Planning around the next block", "Avery reported that the buffer helped once, but the upcoming block will change the two reliable study windows used in the current plan.", "We sketched an alternate schedule and identified what can be reviewed independently if the next advising appointment needs to be rescheduled.", "Test the alternate windows and bring the revised calendar when the next academic-block appointment is rebooked.", "At the rescheduled visit, review the trial rather than assuming the previous calendar will still fit."],
    ],
  },
  {
    id: "student-6", name: "Jordan Kim", advisor: "Bucket L. Manyweather, Ph.D.",
    concern: "Jordan is learning how to prioritize first-year coursework and wants to reduce switching among resources while building confidence in explaining core concepts independently. The student prefers a small routine that can be repeated.",
    visits: [
      ["academic", "Choosing a starting resource", "At the initial visit, Jordan described opening several resources for each topic and running out of time before attempting an explanation independently.", "We reviewed the course objectives and selected a primary starting resource, with supplemental material reserved for a specific unresolved question.", "Use one starting resource for two topics and attempt a short explanation before opening anything additional.", "Bring both explanations and describe what prompted any use of supplemental material."],
      ["academic", "Checking understanding before switching", "Jordan completed the explanations and found that one topic needed clarification while the other had felt uncertain despite an accurate basic explanation.", "We practiced checking an explanation against the objective and distinguishing a missing connection from the desire to review everything again.", "Write one specific question before changing resources and stop when that question has a usable answer.", "Review whether the question-first rule reduces switching and preserves time for practice."],
      ["career", "Connecting curiosity with exploration", "Jordan used the question-first rule on several topics and asked how to approach career exploration without building another overwhelming resource list.", "We applied the same focused-question approach to learning about clinical work and discussed keeping early interests broad during the first year.", "Select one introductory profile and write a question about a clinical responsibility that sounds unfamiliar.", "Bring the question to a future career event or conversation and record the explanation in plain language."],
      ["academic", "Making group study purposeful", "Jordan reported fewer resource changes but found that group study sometimes expanded into reviewing every detail rather than checking the chosen objectives.", "We discussed setting a short agenda and alternating explanations so each participant can identify a gap before the group revisits source material.", "Try a group session with two objectives and end by writing an independent explanation of one concept.", "Compare the final explanation with the starting question and decide what group format was useful."],
      ["career", "Interpreting a new clinical role", "Jordan asked the profile question at an introductory event and learned that the unfamiliar responsibility varies with the clinician's setting and team.", "We discussed preserving that uncertainty in the reflection and avoiding conclusions based on a single account of clinical work.", "Record the example, the setting in which it occurred, and one question for a later contrasting experience.", "Return to the reflection when a relevant opportunity arises rather than adding multiple activities immediately."],
      ["academic", "Setting next-block priorities", "Jordan's group trial stayed focused on two objectives, but the student anticipates difficulty choosing priorities when several new topics arrive together.", "We used an upcoming week to practice selecting essential objectives and setting aside optional resources until an actual gap appears.", "Draft three priorities for the next block and bring them to the pending advising appointment for review.", "Check whether those priorities fit the new schedule and revise the resource plan only where a concrete need emerges."],
    ],
  },
  {
    id: "student-7", name: "Maya Patel", advisor: "Michael O'Leary, M.Ed.",
    concern: "Maya is using clerkship experiences to clarify interests while trying to maintain a manageable learning routine and capture specific feedback before details are forgotten. Brief observations will guide discussion as clinical settings and supervisors change.",
    visits: [
      ["academic", "Capturing clerkship learning needs", "At the initial meeting, Maya described receiving useful feedback during busy clinical days but struggling to turn it into a clear practice priority afterward.", "We designed a brief end-of-day reflection with one observation, one learning question, and one action connected to available supervision.", "Record three short reflections and choose one recurring question to discuss with the clinical teaching team.", "Review whether the reflection is brief enough to maintain and produces a useful learning priority."],
      ["career", "Comparing clerkship experiences", "Maya's reflections captured differences in team interactions and patient contact, but the student was unsure which observations reflected specialty versus local setting.", "We built a comparison around specific experiences and marked conclusions that would require another setting or conversation to examine.", "Compare two clerkship moments using patient relationships, team roles, and the kind of work that held attention.", "Bring one contrast and one uncertainty to the next career visit rather than ranking entire specialties."],
      ["academic", "Turning feedback into practice", "Maya identified a recurring need to organize oral presentations more clearly and discussed that goal with the clinical teaching team.", "We translated the feedback into a small preparation routine and encouraged seeking feedback on one observable aspect of the next supervised presentation.", "Use a brief presentation outline and ask the supervisor for feedback on the sequence of information.", "Review the feedback received and decide whether to retain the outline or revise a particular transition."],
      ["career", "Preparing mentor questions", "Maya's comparison highlighted interest in longitudinal relationships, with uncertainty about how those relationships differ across outpatient and hospital-based work.", "We drafted mentor questions grounded in the recorded experiences and discussed seeking examples of ordinary work as well as memorable cases.", "Ask a mentor about continuity across settings and record one example that broadens the current comparison.", "Review how the example changes the questions Maya wants to bring to residency-oriented conversations."],
      ["academic", "Maintaining reflection during transitions", "Maya reported clearer sequencing after trying the presentation outline, but an approaching clerkship transition will change the opportunities to practice the same routine.", "We separated transferable preparation habits from setting-specific expectations and discussed asking the new team how feedback is usually shared.", "Keep the short reflection format and identify one feedback opportunity early in the next clerkship.", "Check whether the new team's expectations require a different learning priority or a revision to the outline."],
      ["career", "Preparing for residency conversations", "Maya's mentor conversation clarified one continuity question and generated new questions about training environments that support the student's developing interests.", "We organized those questions into a concise conversation agenda without treating them as a finalized specialty or program preference list.", "Bring the agenda and two clerkship reflections to the career appointment once the proposed meeting time is settled.", "Use that visit to distinguish questions answerable now from those that need additional clinical experience."],
    ],
  },
  {
    id: "student-8", name: "Noah Williams", advisor: "Cameron Mastin, M.Ed.",
    concern: "Noah is organizing residency preparation during the advanced phase and wants application tasks, clinical learning, and mentor feedback to fit into a realistic sequence of work.",
    visits: [
      ["academic", "Mapping advanced-phase commitments", "At the initial meeting, Noah brought a task list that mixed clinical preparation, application writing, and administrative work without estimating the time each requires.", "We separated fixed commitments from flexible tasks and identified small writing windows that would not displace preparation for the clinical day.", "Draft a two-week calendar and estimate the effort for one writing task before adding more work.", "Compare the estimate with actual time used and adjust the next calendar from that observation."],
      ["career", "Organizing application evidence", "Noah's calendar revealed that a writing task needed more preparation than expected because relevant examples were scattered across several old reflections.", "We discussed gathering concrete experiences before polishing prose and distinguishing what the student did from what the team accomplished.", "Select three experiences and write a few factual lines describing the role, contribution, and learning from each.", "Review the examples for clarity and identify which need more context before requesting mentor feedback."],
      ["academic", "Protecting clinical learning time", "Noah assembled the examples but used a planned clinical-preparation block to continue editing, leaving the next day's learning questions underdeveloped.", "We reviewed the calendar and established a stopping point for writing so application work does not repeatedly consume the same preparation window.", "Keep writing within a defined block and prepare one clinical learning question before reopening application materials.", "Check whether the stopping point works in practice and revise the task size if editing still runs over."],
      ["career", "Requesting focused mentor feedback", "Noah revised the experience descriptions and identified one example where the contribution was clear but the explanation of learning remained vague.", "We prepared a focused feedback request and discussed asking about clarity and specificity rather than seeking a prediction of application outcomes.", "Send the selected draft to a mentor with two questions and keep a copy of the version being reviewed.", "Compare the returned feedback with the intended message and decide which revisions improve accuracy."],
      ["academic", "Sequencing revisions around rotations", "Noah maintained the clinical-preparation block during the trial, but anticipated mentor revisions may arrive during a busier rotation week.", "We separated essential factual corrections from optional stylistic work and reserved a small revision window based on the upcoming rotation schedule.", "Place essential corrections first and keep an explicit list of optional revisions for a later available block.", "Review whether the sequence protects clinical preparation while still making visible progress on application tasks."],
      ["career", "Preparing an application-planning agenda", "Noah received mentor feedback and made factual clarifications; the remaining questions concern how the selected experiences fit together in the overall application narrative.", "We assembled an agenda for the next advising conversation and encouraged verifying current process details through the student's official application resources.", "Bring the revised examples, unresolved questions, and current task calendar when the application-planning visit is rescheduled.", "At the rebooked visit, review the narrative and task order without assuming a cancelled appointment completed that discussion."],
    ],
  },
];

export function syntheticAdvisingHistories(isoAt: (days: number, hour: number, minute?: number) => string) {
  const appointments = [];
  const encounterRecords = [];
  for (const student of stories) {
    for (const [index, [service, subject, progress, guidance, action, followUp]] of student.visits.entries()) {
      const day = [-70, -56, -42, -28, -21, -14][index];
      const hour = 9 + (Number(student.id.split("-")[1]) % 7);
      const id = `advising-history-${student.id}-${index + 1}`;
      const studentRecap = `${action} ${followUp}`;
      appointments.push({
        id, studentId: student.id, studentName: student.name,
        serviceName: service === "academic" ? "Academic advising" : "Career advising",
        providerName: service === "academic" ? student.advisor : "Art Avila, M.Ed.",
        subject, startsAt: isoAt(day, hour), endsAt: isoAt(day, hour, 30),
        modality: index % 2 === 0 ? "in_person" : "teams", status: "completed",
        sandbox: true, requestOrigin: "student", studentRecap,
      });
      encounterRecords.push({
        appointmentId: id,
        workingNotes: `${student.concern}\n\n${progress} ${guidance}\n\nAgreed next step: ${action} Follow-up: ${followUp}`,
        studentRecap,
        structuredData: {
          categories: [service === "academic" ? "learning_strategy" : "career_exploration"],
          interventions: [subject], referrals: [], followUp: [followUp],
        },
        revision: 1, updatedAt: isoAt(day, hour, 45), publishedAt: isoAt(day, hour, 45),
      });
    }
  }
  return { appointments, encounterRecords };
}

// Saved entries win, including intentionally edited or blank notes. Only absent
// example IDs are backfilled; user-created entries retain their original order.
export function mergeMissingExamples<T>(saved: T[], examples: T[], key: (item: T) => string): T[] {
  const existing = new Set(saved.map(key));
  return [...saved, ...examples.filter((item) => !existing.has(key(item)))];
}
